### ISSUE TITLE
Figure out what to do with Windows-related issues

### ISSUE THREAD

**Issue by jrosdahl** [ccache/ccache#305]
I don't have bandwidth to evaluate the currently open issues related to Windows stuff.

@afbjorklund: Would it be possible for you to give a recommendation on what do with these (apply as is, close without applying, rebase/rework, etc.)?

#69 ("Add appveyor, Windows ci, support")
#119 ("Fix the MinGW tests")
#122 ("Fix and re-enable mingw build")
#169 ("Cleaning up the build system")
#170 ("Windows: quicktest hangs on Cygwin, test should support MSYS2")
#246 ("Added remaining changes, to make it run on MSYS")
#247 ("CI: add Appveyor script")
#256 ("Travis wine")

See also: https://github.com/ccache/ccache/labels/windows

**Comment by afbjorklund** [comment]
@jrosdahl : sure, I will look them through and rebase where needed.
I have access to Windows, even if I don't use it for any development.

**Comment by afbjorklund** [comment]
Checklist:
- [X] Fix the MinGW build (Windows): #72 #73
- [ ] Fix the MSYS build (Cygwin): #170 #246
- [ ] Add Appveyor build/test (x 3): #69 #247
  - [ ] MSYS2 MinGW 32-bit (`MINGW32_NT-*`)
  - [ ] MSYS2 MinGW 64-bit (`MINGW64_NT-*`)
  - [ ] MSYS2 MSYS (`MSYS_NT-*`)
- [ ] Try to get the Travis MinGW test running: #256
- [ ] Fix the outstanding issues: #119 #122 

Getting stuff running with Visual Studio and other build systems is currently **not** a priority. #169 #259

We still have Win32 as the default target, since the Win64 support with Linux tools is not very good yet...
Being able to cross-compile and emulate is critical, since most developers don't have access to Windows.

**Comment by peterbud** [comment]
@afbjorklund let me know if I can help, happy to help you with MSYS2/MINGW32/MINGW64 builds

**Comment by afbjorklund** [comment]
For MinGW I'm going to close all of them, MSYS2 is still OK.
